# Generated by Django 5.1.4 on 2025-01-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='dni')),
                ('user_type', models.CharField(choices=[('a', 'admin'), ('j', 'jugador'), ('o', 'organizador'), ('r', 'arbitro')], default='j', max_length=1, verbose_name='tipo de usuario')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='apellido')),
                ('phone', models.IntegerField(verbose_name='telefono')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='direccion')),
                ('picture', models.ImageField(blank=True, default='media/default-user.png', null=True, upload_to='', verbose_name='imagen')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre del torneo')),
                ('start_date', models.DateField(verbose_name='fecha inicio')),
                ('end_date', models.DateField(verbose_name='fecha fin')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='organizador')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre de equipo')),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='organizador id')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='nombre del equipo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(choices=[(3, 'w'), (1, 'd'), (0, 'l')], verbose_name='puntaje')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='equipo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament', verbose_name='torneo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tournament', 'team_id'), name='unique_score_per_team')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha del partido')),
                ('time', models.TimeField(verbose_name='hora del partido')),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='api.team', verbose_name='equipo visitante')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='api.team', verbose_name='equipo local')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournament', verbose_name='torneo')),
                ('referee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='arbitro')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('team_home', models.F('team_away')), _negated=True), name='prevent_self_match')],
            },
        ),
    ]
